FROM supervisely/base-py-sdk:6.73.231

RUN pip3 install pycocotools==2.0.7
RUN pip3 install typing-extensions==4.8.0
RUN pip3 install labelbox==3.67.0
RUN pip3 install shapely==2.0.2
RUN pip3 install protobuf==3.20.3

LABEL python_sdk_version=6.73.231